import "./globals.css";
import { inter } from "@/auxiliary/fonts";

export const metadata = {
  title: "Social Links Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased flex flex-col items-center justify-center h-screen bg-design-grey-900`}
      >
        {children}
      </body>
    </html>
  );
}
